name: apk_basket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
├── flutter:          
│   └── sdk: flutter  

└── flame: ^1.17.0    
  
  
  # UI
cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# HANYA SATU SECTION flutter: INI
flutter:
  uses-material-design: true
  
